from pathlib import Path
import re

ROOT = Path('.')

def read(path): return (ROOT / path).read_text()
def write(path, text): (ROOT / path).write_text(text)
def replace_once(text, old, new, label):
    if old not in text: raise SystemExit(f'missing {label}')
    return text.replace(old, new, 1)
def sub_once(text, pattern, repl, label, flags=0):
    out, count = re.subn(pattern, repl, text, count=1, flags=flags)
    if count != 1: raise SystemExit(f'{label}: expected 1 replacement, got {count}')
    return out

# PROJECT_PROFILE
p = 'docs/project/PROJECT_PROFILE.md'
t = read(p)
t = replace_once(t,
    '**Initialized — 2026-08-25; refreshed 2026-08-31 through accepted b67 production transport Runtime, b69 daily-chat defect evidence, and exact b70 Code/scope/Push+PR CI/Artifact/package verification.**',
    '**Initialized — 2026-08-25; refreshed 2026-08-31 through accepted b67 production transport Runtime, exact b71 Runtime rejection evidence, and exact b72 Code/scope/Simulator/Push+PR CI/Artifact/package verification.**',
    'profile refresh line')
insert = '''## Exact b72 current Candidate\n\nBuild72 is the current real-device Candidate after the user's exact b71 comparison rejected the previous reasoning/tool interaction hierarchy and process-global cross-conversation Send serialization. b72 keeps the accepted b67 protected-Send route/selector/challenge/SSE grammar while changing only the evidenced Native presentation/concurrency owners.\n\nIdentity: Candidate `DEV-send-stream-0.1.0-b72`, `0.1.0 (72)`, exact product/config source `d20536db37a028556c8032e7c74912805ade785c`, code commit `451fa0cb58bbbc681a97d3156bada50357a6067e`, Push `33403473989/99525205970`, PR `33403478927/99525223287`, Artifact `9762189417`, ZIP `sha256:5107cedc43b3e5a096da60db9acc2f0705c30bb81be8134f1373dba6f929c1b9`, IPA `ff9d37022a310cab3eea0bb3c298e3d3ec8b0d3057f7256da4f0543dab18b53c`, source marker `d20536db37a0`, minimum iOS14, arm64. Evidence ladder: Code/exact scope/Simulator compile/Push+PR CI/Artifact/package verified; **Runtime pending**; Stable/Frozen No.\n\nImplementation boundary: first-level `思考了 <duration>` expands/collapses the entire inline chronological reasoning+tool timeline; concrete tool rows open an ordered tools-only/input-only sheet; one shared service-backed duration formatter renders seconds below 60 and accumulated minutes thereafter (minutes remain the maximum unit); covered Web executor ownership is keyed per conversation so unrelated conversations are not process-globally serialized, while Repository response ownership remains per conversation and each executor retains the b67 one-Send gate.\n\n'''
t = replace_once(t, '## Current product interaction target\n', insert + '## Current product interaction target\n', 'profile b72 insert')
t = sub_once(t,
    r'## Current next Candidate boundary\n\n.*?\n\n## Remaining Unknown / Unverified',
    '''## Current next Candidate boundary\n\nBuild72 is permanently reserved because Artifact `9762189417` exists. Exact b72 real-device evidence is now the only current Candidate gate. Do not allocate b73 unless b72 Runtime yields a concrete defect or next evidence need. The gate must verify first-level inline reasoning/tool expansion, minute-level duration display, tools-only/input-only secondary sheet behavior, bounded tool icons, and A+B simultaneous generation with independent per-conversation ownership while preserving b67 one-Send transport and b38 geometry.\n\n## Remaining Unknown / Unverified''',
    'profile candidate boundary', re.S)
t = replace_once(t, 'b39-b70 are permanently reserved.', 'b39-b72 are permanently reserved.', 'profile reserve range')
write(p, t)

# PROJECT_STATE
p = 'docs/project/PROJECT_STATE.md'
t = read(p)
t = replace_once(t,
    '_Last updated: 2026-08-31 through accepted b67 production transport Runtime, b69 Runtime defect evidence, and exact b70 Code/scope/Push+PR CI/Artifact/package verification. Phase 9 `DEV-send-stream` remains Active at the b70 human Runtime gate. Stable/Frozen Send remains No._',
    '_Last updated: 2026-08-31 through accepted b67 production transport Runtime, exact b71 Runtime rejection evidence, and exact b72 Code/scope/Simulator/Push+PR CI/Artifact/package verification. Phase 9 `DEV-send-stream` remains Active at the b72 human Runtime gate. Stable/Frozen Send remains No._',
    'state refresh line')
t = sub_once(t,
    r'Latest exact product Candidate is \*\*`DEV-send-stream-0\.1\.0-b70` / `0\.1\.0 \(70\)`\*\*:\n\n.*?b39-b70 are permanently reserved\.',
    '''Latest exact product Candidate is **`DEV-send-stream-0.1.0-b72` / `0.1.0 (72)`**:\n\n- exact product/config source `d20536db37a028556c8032e7c74912805ade785c`; code commit `451fa0cb58bbbc681a97d3156bada50357a6067e` with direct parent `2aaee7f6fa143c1c3426ca89d2d52b42949daf86`;\n- isolated assembly exact four-file scope audit, `git diff --check` and Xcode 16.4 iOS Simulator compile passed;\n- Push `33403473989 / 99525205970` and PR `33403478927 / 99525223287` — success;\n- Artifact `9762189417`; ZIP `sha256:5107cedc43b3e5a096da60db9acc2f0705c30bb81be8134f1373dba6f929c1b9`;\n- IPA `sha256:ff9d37022a310cab3eea0bb3c298e3d3ec8b0d3057f7256da4f0543dab18b53c`;\n- independently unpacked package `0.1.0 (72)` / Candidate b72 / source `d20536db37a0` / minimum iOS14 / arm64.\n\nb72 retains b67 protected-Send/SSE ownership and b69 ordered response chronology, while implementing the latest explicit b71 Runtime corrections: first-level inline whole-timeline reasoning disclosure, tools-only/input-only secondary tool list, centralized service-backed minute-level reasoning duration formatting, bounded tool identity presentation, and per-conversation covered executor ownership so unrelated conversations are not globally serialized. No retry/replay/poll/timer/watchdog/fallback or second state owner was added. Evidence ladder: **Code / exact scope / Simulator compile / Push+PR CI / Artifact / package verified / Runtime pending / Stable-Frozen No.** b39-b72 are permanently reserved.''',
    'state latest candidate block', re.S)
t = replace_once(t, 'exact b70 daily-chat parity/auth-lifecycle Runtime is the immediate gate.', 'exact b72 reasoning/tool hierarchy + simultaneous-generation Runtime is the immediate gate.', 'state immediate gate')
t = sub_once(t,
    r'## Current exact Runtime gate\n\n.*?\n\n## Remaining Unknown / Unverified',
    '''## Current exact Runtime gate\n\nInstall exact b72 Artifact `9762189417` / IPA SHA `ff9d3702...8b53c` on the primary iPhone/iOS17 device. Verify Candidate/source marker `d20536db37a0`, clear diagnostics, then confirm: the main `思考了 <duration>` control expands/collapses the entire chronological reasoning+tool timeline inline; duration stays seconds below 60 and accumulated minutes thereafter without hours; tapping concrete tool rows opens one ordered tools-only sheet with direct authorized input and no reasoning/output section; unknown/non-GitHub tools do not masquerade as GitHub; A can continue generating while B independently sends/generates with one active response per conversation; hidden A survives navigation; b67 one-Send transport, hidden-thought exclusion and b38 geometry do not regress. Export diagnostics after terminal(s).\n\n## Remaining Unknown / Unverified''',
    'state runtime gate', re.S)
write(p, t)

# MODULE_STATUS
p = 'docs/project/MODULE_STATUS.md'
t = read(p)
t = t.replace('| Build/runtime metadata | **b70 exact identity; Runtime pending** | Xcode settings / built `Info.plist` | `0.1.0 (70)`, source `fb83be916383...`, Artifact `9752289536`; b39-b70 reserved. |', '| Build/runtime metadata | **b72 exact identity; Runtime pending** | Xcode settings / built `Info.plist` | `0.1.0 (72)`, source `d20536db37a0...`, Artifact `9762189417`; b39-b72 reserved. |')
t = t.replace('| IPA build / CI packaging | **Stable capability; b70 Artifact valid** | `scripts/build_ipa.sh`, workflow | Push `33377045570/99440767755`, PR `33377049590/99440781050`, Artifact `9752289536`, IPA `8084e2ac...a44a`; package b70/source `fb83be916383`/iOS14/arm64. |', '| IPA build / CI packaging | **Stable capability; b72 Artifact valid** | `scripts/build_ipa.sh`, workflow | Push `33403473989/99525205970`, PR `33403478927/99525223287`, Artifact `9762189417`, IPA `ff9d3702...8b53c`; package b72/source `d20536db37a0`/iOS14/arm64. |')
t = t.replace('| Covered official-Web protected Send executor | **Production transport Runtime accepted b67; b70 keyboard-only correction Runtime pending** | `CoveredWebSendExecutor` + TD-029 + `WEB_SEND_ADAPTER.md` | b67 passed one protected Send -> HTTP200 SSE -> terminal/reconcile. b70 retains route/selectors/SSE grammar and only suppresses covered programmatic keyboard focus. |', '| Covered official-Web protected Send executor | **Production transport Runtime accepted b67; b72 per-conversation ownership Runtime pending** | `CoveredWebSendExecutor` + TD-029 + `WEB_SEND_ADAPTER.md` | b67 passed one protected Send -> HTTP200 SSE -> terminal/reconcile. b72 retains route/selectors/challenge/SSE grammar and keys covered executors per conversation so unrelated conversations are not process-globally serialized; exact A+B Runtime pending. |')
t = t.replace('| Streaming / Send | **Active — b67 transport accepted; b70 daily-chat Runtime gate** | `DEV-send-stream`; PR #29; TD-029 | b70 exact source/Push+PR CI/Artifact/package verified; keyboard/user-row/tool-detail/auth-lifecycle corrections remain Runtime pending. |', '| Streaming / Send | **Active — b67 transport accepted; b72 interaction/concurrency Runtime gate** | `DEV-send-stream`; PR #29; TD-029 | b72 exact source/scope/Simulator/Push+PR CI/Artifact/package verified; inline reasoning/tool hierarchy, minute-level duration and A+B simultaneous generation remain Runtime pending. |')
t = t.replace('| User-visible reasoning | **Production stream passed b67; ordered b70 presentation Runtime pending** | `ConversationRepository` + `DEV-send-stream` | b69 ordered segments retained; b70 tightens spacing/divider/detail presentation only; exact `reasoning_ended` remains final authority; hidden thoughts prohibited. |', '| User-visible reasoning | **Production stream passed b67; b72 first-level hierarchy Runtime pending** | `ConversationRepository` + `DEV-send-stream` | b69 ordered segments retained; b72 makes `思考了 <duration>` the inline whole-timeline disclosure and centralizes service-backed seconds/minutes formatting; exact `reasoning_ended` remains final authority; hidden thoughts prohibited. |')
t = t.replace('| Tool activity presentation | **b70 Code/CI/Artifact/package verified; Runtime pending** | `DEV-send-stream` | Tool event order/in-place completion retained; b70 restores authorized nested details, adds bounded local icons and compact deterministic spacing/divider. |', '| Tool activity presentation | **b72 Code/CI/Artifact/package verified; Runtime pending** | `DEV-send-stream` | Tool event order/in-place completion retained; concrete tool rows open one ordered tools-only/input-only sheet, output hidden; bounded identity icons only. |')
t = t.replace('- b70 source `fb83be9163838f78abfa47903e67f27b6f66ec52`, Artifact `9752289536`, IPA `8084e2ac...a44a` is the current daily-chat parity/auth-lifecycle Runtime candidate; package identity independently verified.', '- b72 source `d20536db37a028556c8032e7c74912805ade785c`, Artifact `9762189417`, IPA `ff9d3702...8b53c` is the current reasoning/tool hierarchy + simultaneous-generation Runtime candidate; package identity independently verified.')
t = t.replace('- b39-b70 are reserved. Phase 9 Stable/Frozen: No.', '- b39-b72 are reserved. Phase 9 Stable/Frozen: No.')
write(p, t)

# TECHNICAL_DECISIONS
p = 'docs/project/TECHNICAL_DECISIONS.md'
t = read(p)
t = sub_once(t,
    r'### TD-014 — Reasoning UI includes expandable user-visible detail and two-pulse transition haptic\n- \*\*Status\*\*:.*?\n- \*\*Decision\*\*:.*?\n\n### TD-015',
    '''### TD-014 — Reasoning UI includes expandable user-visible detail and two-pulse transition haptic\n- **Status**: Confirmed requirement; production transport Runtime accepted b67; b72 interaction hierarchy/package verified, Runtime pending\n- **Decision**: When `ConversationRepository` receives explicitly user-visible reasoning/tool events, preserve chronological order inside one assistant turn (`reasoning -> tool -> reasoning -> tool -> ... -> final`). Tool completion updates the existing tool segment in place; later reasoning remains below the preceding tool. The first-level `思考了 <duration>` / `思考过程` control expands/collapses the entire visible reasoning+tool timeline inline. A concrete tool row may open a secondary ordered tools-only list; reasoning prose stays out of that sheet, authorized tool input is direct, and tool output is hidden in the current product presentation. Reasoning duration uses only service-backed `finished_duration_sec`/`reasoningEnded(durationSec)` and one shared formatter: seconds below 60, accumulated minutes plus remainder at/above 60, no hour unit. Never expose hidden chain-of-thought; `assistant:thoughts` / `inline_cot_expandable_content` remain non-presentational. This hierarchy is grounded by the user's exact official-app comparison; b72 implements it without a second response owner.\n\n### TD-015''',
    'TD-014 block', re.S)
t = replace_once(t,
    'Foreground selection is presentation only; selecting B does not delete A or cancel valid hidden A work. Do not retain raw graph payloads or UIKit hierarchies as cache. No arbitrary normal LRU capacity; memory-warning trimming remains evidence-backed policy. Covered Web Send execution under TD-029 is not another repository.',
    'Foreground selection is presentation only; selecting B does not delete A or cancel valid hidden A work. Unrelated conversations are not globally serialized merely because same-conversation overlap is guarded. b72 keys the covered Web executor by conversation so A and B can own independent protected-Send execution surfaces while `ConversationRepository` remains the sole response/conversation authority; exact simultaneous-generation Runtime remains pending. Do not retain raw graph payloads or UIKit hierarchies as cache. No arbitrary normal LRU capacity; memory-warning trimming remains evidence-backed policy. Covered Web Send execution under TD-029 is not another repository.',
    'TD-019 concurrency sentence')
write(p, t)

# BUILD_TEST_INDEX
p = 'docs/project/BUILD_TEST_INDEX.md'
t = read(p)
anchor = '| `DEV-send-stream-0.1.0-b70` | `DEV-send-stream` | `0.1.0 (70)` | exact source `fb83be9163838f78abfa47903e67f27b6f66ec52`; PR #29 | Assembly `33373254877/99428895016`; Push `33377045570/99440767755`; PR `33377049590/99440781050`; Artifact `9752289536`; ZIP `sha256:bdf09b246ff259ee80d46acfad675713c1a0b51aee3b44f7ea9f0a7e67eafde0`; IPA `8084e2ace5926b7ee6a790f3eeb2445a2c4ce1fee67d8953300aca93a446a44a`; Release/source `fb83be916383`/iOS14/`[1,2]`/arm64 | Daily-chat parity correction: suppress covered-Web keyboard, response-local optimistic user row, restored exact-parent GitHub nested details + bounded icons + compact spacing/divider, and stale transient 401/403 invalidation with 403 account-identity preservation/no automatic retry. | **Code/scope/static+sim compile/Push+PR CI/Artifact/package verified; Runtime pending; permanently reserved** |\n'
rows = anchor + '| `DEV-send-stream-0.1.0-b71` | `DEV-send-stream` | `0.1.0 (71)` | exact source `af8d4a4b291c05fb63a50cee0261c06d7ce474d3`; PR #29 | Push `33388396118/99476130099`; PR `33388399484/99476140778`; Artifact `9756491305`; ZIP `sha256:74b554c98333e365b03073a39b0286f966b98c94ec2a695d62b81cb4f8f7bda0`; IPA `a9322dba9351842ac2d2374a1f8792129fe64750a1c79da514e2444bb785fd65`; Release/source `af8d4a4b291c`/iOS14/arm64 | Exact user iPhone/iOS17 comparison rejected the secondary-sheet reasoning hierarchy and process-global cross-conversation Send serialization; package identity remains valid. | **Runtime rejected presentation/concurrency behavior; permanently reserved** |\n| `DEV-send-stream-0.1.0-b72` | `DEV-send-stream` | `0.1.0 (72)` | exact product/config source `d20536db37a028556c8032e7c74912805ade785c`; code `451fa0cb58bbbc681a97d3156bada50357a6067e`; PR #29 | Push `33403473989/99525205970`; PR `33403478927/99525223287`; Artifact `9762189417`; ZIP `sha256:5107cedc43b3e5a096da60db9acc2f0705c30bb81be8134f1373dba6f929c1b9`; IPA `ff9d37022a310cab3eea0bb3c298e3d3ec8b0d3057f7256da4f0543dab18b53c`; Release/source `d20536db37a0`/iOS14/arm64 | First-level inline whole-timeline reasoning disclosure; service-backed seconds/minutes duration formatter; concrete tool row -> ordered tools-only/input-only sheet; per-conversation covered executors for unrelated A+B generation while retaining b67 one-Send gate. | **Code/scope/Simulator/Push+PR CI/Artifact/package verified; Runtime pending; permanently reserved** |\n'
t = replace_once(t, anchor, rows, 'build index b70 anchor')
t = sub_once(t,
    r'## Current Phase 9 Send / Stream evidence boundary\n\n.*\Z',
    '''## Current Phase 9 Send / Stream evidence boundary\n\n- Exact b39-b72 Candidate identities are permanently reserved once emitted; never rebuild/reuse them.\n- b42 browser-challenge evidence still blocks pure-native/transient-auth protected Send; TD-029 covered official-Web protected-Send architecture remains current.\n- b67 production existing-conversation transport is Runtime accepted: one local Send -> one protected page-owned Send -> HTTP200 SSE -> Repository updates -> terminal/reconcile.\n- b69 chronological `reasoning -> tool -> reasoning -> tool -> final` timeline direction and exact-parent tool-result association remain retained.\n- b71 package is valid but exact iPhone/iOS17 comparison rejected its reasoning/tool interaction hierarchy and process-global cross-conversation Send serialization.\n- b72 exact source `d20536db37a028556c8032e7c74912805ade785c` passed isolated exact scope + `git diff --check` + Xcode 16.4 Simulator compile, Push CI `33403473989/99525205970`, PR CI `33403478927/99525223287`, and produced canonical Artifact `9762189417`. ZIP/IPA/package identity were independently verified.\n- b72 user-visible duration uses service-backed duration only: `<60s -> Ns`; `>=60s -> Nm` or `Nm Ns`; minutes remain the maximum unit.\n- b72 first-level thinking disclosure owns the inline chronological reasoning+tool timeline; concrete tool rows enter one ordered tools-only/input-only sheet with tool output hidden. Hidden `assistant:thoughts` / `inline_cot_expandable_content` remain prohibited.\n- b72 covered executor ownership is per conversation; initial invariant remains at most one active response per conversation. Unrelated conversations must not be globally serialized. No retry/queue timer/polling/fallback/duplicate Send was added.\n- **Current gate:** exact b72 iPhone/iOS17 Runtime. Verify hierarchy/duration/tool-sheet/icon behavior plus A active -> B independent Send/generation, while preserving b67 one-Send transport, hidden-response navigation, hidden-thought exclusion and b38 geometry.\n- Do not allocate b73 unless exact b72 Runtime yields a concrete defect or next evidence need.\n''',
    'build phase9 boundary', re.S)
write(p, t)

print('b72 durable docs patched')
