from pathlib import Path


def replace_once(path: Path, old: str, new: str, label: str) -> None:
    text = path.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected exactly 1 anchor, found {count}")
    path.write_text(text.replace(old, new, 1))


# PROJECT_PROFILE
p = Path("docs/project/PROJECT_PROFILE.md")
text = p.read_text()
text = text.replace(
    "**Initialized — 2026-08-25; refreshed 2026-08-31 through accepted b67 production transport Runtime, b69 daily-chat defect evidence, and exact b70 Code/scope/Push+PR CI/Artifact/package verification.**",
    "**Initialized — 2026-08-25; refreshed 2026-08-31 through accepted b67 production transport Runtime, positive b72 tested cross-conversation simultaneous-generation Runtime, b72 presentation rejection, and exact b73 Code/scope/Simulator/Push+PR CI/Artifact/package verification.**",
)
text = text.replace(
    "- Production native conversation/list/read/recovery/**response lifecycle** authority: one `ConversationRepository` in `Conversation/ConversationFeature.swift`; b70 optimistic user/live assistant state, ordered reasoning/tools and stale copied-transport invalidation remain Repository-owned.",
    "- Production native conversation/list/read/recovery/**response lifecycle** authority: one `ConversationRepository` in `Conversation/ConversationFeature.swift`; optimistic user/live assistant state, ordered reasoning/tools and per-conversation response snapshots remain Repository-owned. b73 changes presentation state only and does not add a second response owner.",
)
old_section_start = text.index("## Exact b70 current Candidate")
old_section_end = text.index("## Current product interaction target")
new_section = '''## Exact b73 current Candidate\n\nBuild73 is the presentation-only correction after b72 Runtime accepted the tested A-generating + B-send simultaneous-generation path but rejected main reasoning/tool density and default live disclosure behavior. b73 preserves the b72 per-conversation covered executor implementation and b67 protected-Send/SSE path.\n\nIdentity: Candidate `DEV-send-stream-0.1.0-b73`, `0.1.0 (73)`, exact source `4edda892a04a1a07f4a07e74b135b969ea82193e`; product code commit `0e3eb6cad4cc56e8c2bcb946724d7cf1d4d55701`; assembly `33408291419` success after one tooling-only assertion failure; Push `33408695143/99542593642`; PR `33408698697/99542605699`; Artifact `9764247402`; ZIP `sha256:718c2f4fd0fe3521f7469f5996f6944960ffdaa3b2829c0c17e340ebd41dd206`; IPA `8285ba9d5f63207feb2eaf722ec722a886f3ee88956236a89a716ad58b884113`; package source marker `4edda892a04a`, Release, iOS14 minimum, arm64. Evidence: Code/scope/Simulator/Push+PR CI/Artifact/package verified; **Runtime pending**; Stable-Frozen No.\n\nBuild73 main inline reasoning shows body-scale primary reasoning prose and only meaningful service-authored tool titles with looser tool row rhythm, while the tools-only sheet retains the ordered call list. Live reasoning auto-opens once when visible reasoning/tool content first arrives and auto-collapses once on exact `reasoning_ended`; later user disclosure state remains user-owned.\n\n'''
text = text[:old_section_start] + new_section + text[old_section_end:]
old_boundary_start = text.index("## Current next Candidate boundary")
old_boundary_end = text.index("## Remaining Unknown / Unverified")
new_boundary = '''## Current next Candidate boundary\n\nBuild73 is the current exact real-device presentation Runtime candidate. b39-b73 are permanently reserved. Do not allocate b74 before exact b73 Runtime supplies a concrete defect/next evidence need. The gate must verify live default-expanded reasoning, one automatic collapse at exact reasoning end, user-owned disclosure after that transition, concise meaningful main tool rows with looser spacing/body-scale reasoning prose, tools-only/input-only sheet preservation, and no regression to the b72 tested cross-conversation simultaneous-generation path.\n\n'''
text = text[:old_boundary_start] + new_boundary + text[old_boundary_end:]
text = text.replace(
    "Exact b70 daily-chat parity/auth-lifecycle Runtime, new-chat authoritative identity timing, server Stop mechanism, simultaneous cross-conversation generation, connector detail beyond the evidenced GitHub mapping, Native first/exclusive resume, 5/15-minute background execution, WebContent termination, lower iOS/iPad, non-personal workspace/account switching and native attachment handoff remain Unknown / Unverified unless explicitly tested. CI/Artifact success is never Runtime proof.",
    "Exact b73 presentation Runtime, new-chat authoritative identity timing, server Stop mechanism, broader cross-conversation/service concurrency beyond the exact b72 A/B test, connector detail beyond the evidenced GitHub mapping, Native first/exclusive resume, 5/15-minute background execution, WebContent termination, lower iOS/iPad, non-personal workspace/account switching and native attachment handoff remain Unknown / Unverified unless explicitly tested. CI/Artifact success is never Runtime proof.",
)
p.write_text(text)

# PROJECT_STATE
p = Path("docs/project/PROJECT_STATE.md")
text = p.read_text()
text = text.replace(
    "_Last updated: 2026-08-31 through accepted b67 production transport Runtime, b69 Runtime defect evidence, and exact b70 Code/scope/Push+PR CI/Artifact/package verification. Phase 9 `DEV-send-stream` remains Active at the b70 human Runtime gate. Stable/Frozen Send remains No._",
    "_Last updated: 2026-08-31 through accepted b67 production transport Runtime, positive b72 tested cross-conversation simultaneous-generation Runtime, b72 presentation rejection, and exact b73 Code/scope/Simulator/Push+PR CI/Artifact/package verification. Phase 9 `DEV-send-stream` remains Active at the b73 human Runtime gate. Stable/Frozen Send remains No._",
)
start = text.index("Latest exact product Candidate is **`DEV-send-stream-0.1.0-b70` / `0.1.0 (70)`**:")
end = text.index("## b65 accepted probe predecessor")
replacement = '''Latest exact product Candidate is **`DEV-send-stream-0.1.0-b73` / `0.1.0 (73)`**:\n\n- exact product/config source `4edda892a04a1a07f4a07e74b135b969ea82193e`; product code commit `0e3eb6cad4cc56e8c2bcb946724d7cf1d4d55701`;\n- assembly `33408291419` — exact presentation/config scope audit, `git diff --check` and Xcode 16.4 iOS Simulator compile passed after the earlier tooling-only assertion failure `33408115270`;\n- Push `33408695143 / 99542593642` and PR `33408698697 / 99542605699` — success;\n- Artifact `9764247402`; ZIP `sha256:718c2f4fd0fe3521f7469f5996f6944960ffdaa3b2829c0c17e340ebd41dd206`;\n- IPA `sha256:8285ba9d5f63207feb2eaf722ec722a886f3ee88956236a89a716ad58b884113`;\n- independently unpacked package `0.1.0 (73)` / Candidate b73 / source `4edda892a04a` / Release / minimum iOS14 / arm64.\n\nb72 exact iPhone/iOS17 Runtime positively supports the tested A-generating + B-send/generate path and single-digit-ms incremental reasoning-disclosure toggles, but rejects the prior dense main reasoning/tool rendering and default-collapsed live reasoning. b73 changes only `ConversationFeature.swift` plus build/workflow identity: meaningful service-authored tool titles remain in the main timeline, generic `工具调用` rows stay out of the main surface but remain available in the tools-only sheet, reasoning prose uses body-scale primary typography with looser tool rhythm, live reasoning auto-opens once and exact `reasoning_ended` auto-collapses once without repeatedly overriding later manual user state. `RootViewController.swift` is unchanged from b72. Evidence ladder: **Code / exact scope / Simulator compile / Push+PR CI / Artifact / package verified / Runtime pending / Stable-Frozen No.** b39-b73 are permanently reserved.\n\n'''
text = text[:start] + replacement + text[end:]
old_gate_start = text.index("## Current exact Runtime gate")
old_gate_end = text.index("## Remaining Unknown / Unverified")
new_gate = '''## Current exact Runtime gate\n\nInstall exact b73 Artifact `9764247402` / IPA SHA `8285ba9d...84113` on the primary iPhone/iOS17 device. Verify Candidate/source marker, then confirm: first visible live reasoning/tool content defaults expanded; a manual collapse while still reasoning is not reopened by later deltas; an untouched expanded run auto-collapses once on exact reasoning end; later manual disclosure state is not overridden by final deltas; main inline tools are concise meaningful service-authored actions with looser row rhythm and body-scale reasoning prose; generic calls remain accessible in the ordered tools-only/input-only sheet; b72 A/B simultaneous-generation behavior, hidden-thought exclusion and b38 geometry/quick navigation do not regress.\n\n'''
text = text[:old_gate_start] + new_gate + text[old_gate_end:]
text = text.replace(
    "Exact b70 daily-chat parity/auth-lifecycle Runtime, new-chat authoritative identity timing, exact server Stop mechanism, cross-conversation simultaneous server generation, connector-detail schemas beyond the evidenced GitHub mapping, Native first/exclusive resume, 5/15-minute background behavior, WebContent termination recovery, lower iOS/iPad, non-personal workspace/account switching and native attachment handoff remain Unknown / Unverified unless explicitly tested. CI/Artifact success is never Runtime proof.",
    "Exact b73 presentation Runtime, new-chat authoritative identity timing, exact server Stop mechanism, broader cross-conversation/service concurrency beyond the exact b72 A/B test, connector-detail schemas beyond the evidenced GitHub mapping, Native first/exclusive resume, 5/15-minute background behavior, WebContent termination recovery, lower iOS/iPad, non-personal workspace/account switching and native attachment handoff remain Unknown / Unverified unless explicitly tested. CI/Artifact success is never Runtime proof.",
)
p.write_text(text)

# MODULE_STATUS
p = Path("docs/project/MODULE_STATUS.md")
text = p.read_text()
text = text.replace("| Build/runtime metadata | **b70 exact identity; Runtime pending** | Xcode settings / built `Info.plist` | `0.1.0 (70)`, source `fb83be916383...`, Artifact `9752289536`; b39-b70 reserved. |", "| Build/runtime metadata | **b73 exact identity; Runtime pending** | Xcode settings / built `Info.plist` | `0.1.0 (73)`, source `4edda892a04a...`, Artifact `9764247402`; b39-b73 reserved. |")
text = text.replace("| IPA build / CI packaging | **Stable capability; b70 Artifact valid** | `scripts/build_ipa.sh`, workflow | Push `33377045570/99440767755`, PR `33377049590/99440781050`, Artifact `9752289536`, IPA `8084e2ac...a44a`; package b70/source `fb83be916383`/iOS14/arm64. |", "| IPA build / CI packaging | **Stable capability; b73 Artifact valid** | `scripts/build_ipa.sh`, workflow | Push `33408695143/99542593642`, PR `33408698697/99542605699`, Artifact `9764247402`, IPA `8285ba9d...84113`; package b73/source `4edda892a04a`/Release/iOS14/arm64. |")
text = text.replace("| Streaming / Send | **Active — b67 transport accepted; b70 daily-chat Runtime gate** | `DEV-send-stream`; PR #29; TD-029 | b70 exact source/Push+PR CI/Artifact/package verified; keyboard/user-row/tool-detail/auth-lifecycle corrections remain Runtime pending. |", "| Streaming / Send | **Active — b67 transport accepted; b72 tested A/B simultaneous generation positive; b73 presentation Runtime gate** | `DEV-send-stream`; PR #29; TD-029 | b73 exact source/Push+PR CI/Artifact/package verified; transport/concurrency code unchanged from b72/b67; presentation Runtime pending. |")
text = text.replace("| User-visible reasoning | **Production stream passed b67; ordered b70 presentation Runtime pending** | `ConversationRepository` + `DEV-send-stream` | b69 ordered segments retained; b70 tightens spacing/divider/detail presentation only; exact `reasoning_ended` remains final authority; hidden thoughts prohibited. |", "| User-visible reasoning | **Production stream passed b67; b73 official-like presentation Runtime pending** | `ConversationRepository` + `DEV-send-stream` | Ordered segments retained; b73 uses body-scale primary reasoning prose, live auto-open once and exact `reasoning_ended` auto-collapse once; later manual disclosure stays user-owned; hidden thoughts prohibited. |")
text = text.replace("| Tool activity presentation | **b70 Code/CI/Artifact/package verified; Runtime pending** | `DEV-send-stream` | Tool event order/in-place completion retained; b70 restores authorized nested details, adds bounded local icons and compact deterministic spacing/divider. |", "| Tool activity presentation | **b73 Code/CI/Artifact/package verified; Runtime pending** | `DEV-send-stream` | Main timeline keeps meaningful service-authored tool actions with looser rhythm and omits generic fallback rows; ordered tools-only/input-only sheet retains actual eligible calls. No guessed title synthesis. |")
start = text.index("## Current acceptance boundary")
end = text.index("## Auto-refresh rule")
text = text[:start] + '''## Current acceptance boundary\n\n- Stable merged native baseline remains b38.\n- b67 production existing-conversation transport Runtime is accepted.\n- Exact b72 Runtime positively supports the tested A-generating + B-send/generate simultaneous-generation path and the incremental disclosure-performance correction; b72 presentation density/default-live-disclosure behavior is rejected.\n- b73 exact source `4edda892a04a1a07f4a07e74b135b969ea82193e`, Artifact `9764247402`, IPA `8285ba9d...84113` is the current presentation Runtime candidate; package identity independently verified.\n- `ConversationRepository` remains sole response authority; `AuthSessionStore` remains sole account authority; `WEB_SEND_ADAPTER.md` route/SSE contract is unchanged by b73.\n- b39-b73 are reserved. Phase 9 Stable/Frozen: No.\n\n''' + text[end:]
p.write_text(text)

# TECHNICAL_DECISIONS TD-014 only
p = Path("docs/project/TECHNICAL_DECISIONS.md")
text = p.read_text()
old = '''### TD-014 — Reasoning UI includes expandable user-visible detail and two-pulse transition haptic\n- **Status**: Confirmed requirement; production transport accepted b67; ordered production presentation implemented b69, Runtime pending\n- **Decision**: When `ConversationRepository` receives explicitly user-visible reasoning/tool events, preserve chronological order inside one assistant turn (`reasoning -> tool -> reasoning -> tool -> ... -> final`). Tool completion updates the existing tool segment in place; later reasoning remains below the preceding tool. Keep explicit expand/collapse and the accepted reasoning->final transition behavior. Never expose hidden chain-of-thought; `assistant:thoughts` / `inline_cot_expandable_content` remain non-presentational. This ordering is grounded by the user-supplied official ChatGPT recording and b69 implements it without a second response owner.\n'''
new = '''### TD-014 — Reasoning UI includes expandable user-visible detail and two-pulse transition haptic\n- **Status**: Confirmed requirement; production transport accepted b67; tested A/B simultaneous generation positive b72; b73 presentation package verified, Runtime pending\n- **Decision**: When `ConversationRepository` receives explicitly user-visible reasoning/tool events, preserve chronological order inside one assistant turn (`reasoning -> tool -> reasoning -> tool -> ... -> final`). Tool completion updates the existing tool segment in place; later reasoning remains below the preceding tool. The main conversation should remain semantic rather than a raw engineering log: show meaningful service-authored tool-purpose titles, omit fallback generic `工具调用` rows from the main inline surface without destroying the ordered tool list, and never synthesize/merge titles by guess. Visible reasoning prose uses ordinary body-scale primary presentation while tool rows/summary remain secondary with official-like vertical rhythm. During a live generation the first visible reasoning/tool timeline auto-expands once; exact `reasoning_ended` auto-collapses it once; subsequent manual disclosure state remains user-owned. Historical completed reasoning defaults collapsed. Never expose hidden chain-of-thought; `assistant:thoughts` / `inline_cot_expandable_content` remain non-presentational.\n'''
if text.count(old) != 1:
    raise SystemExit("TD-014 anchor mismatch")
p.write_text(text.replace(old, new, 1))

# BUILD_TEST_INDEX append b71-b73 after b70 row
p = Path("docs/project/BUILD_TEST_INDEX.md")
text = p.read_text()
anchor = '| `DEV-send-stream-0.1.0-b70` | `DEV-send-stream` | `0.1.0 (70)` | exact source `fb83be9163838f78abfa47903e67f27b6f66ec52`; PR #29 | Assembly `33373254877/99428895016`; Push `33377045570/99440767755`; PR `33377049590/99440781050`; Artifact `9752289536`; ZIP `sha256:bdf09b246ff259ee80d46acfad675713c1a0b51aee3b44f7ea9f0a7e67eafde0`; IPA `8084e2ace5926b7ee6a790f3eeb2445a2c4ce1fee67d8953300aca93a446a44a`; Release/source `fb83be916383`/iOS14/`[1,2]`/arm64 | Daily-chat parity correction: suppress covered-Web keyboard, response-local optimistic user row, restored exact-parent GitHub nested details + bounded icons + compact spacing/divider, and stale transient 401/403 invalidation with 403 account-identity preservation/no automatic retry. | **Code/scope/static+sim compile/Push+PR CI/Artifact/package verified; Runtime pending; permanently reserved** |'
if text.count(anchor) != 1:
    raise SystemExit("b70 row anchor mismatch")
rows = anchor + '\n' + '''| `DEV-send-stream-0.1.0-b71` | `DEV-send-stream` | `0.1.0 (71)` | exact source `af8d4a4b291c05fb63a50cee0261c06d7ce474d3`; PR #29 | Push/PR CI passed; Artifact `9756491305`; IPA `a9322dba9351842ac2d2374a1f8792129fe64750a1c79da514e2444bb785fd65`; Release/source `af8d4a4b291c`/iOS14/arm64 | Official-like first-level reasoning disclosure + tools-only/input-only sheet direction; user Runtime later found main reasoning/tool density/default live disclosure still off. | **Code/CI/Artifact/package valid; Runtime presentation rejected/superseded; permanently reserved** |\n| `DEV-send-stream-0.1.0-b72` | `DEV-send-stream` | `0.1.0 (72)` | exact source `d20536db37a028556c8032e7c74912805ade785c`; PR #29 | Push `33403473989/99525205970`; PR `33403478927/99525223287`; Artifact `9762189417`; ZIP `sha256:5107cedc43b3e5a096da60db9acc2f0705c30bb81be8134f1373dba6f929c1b9`; IPA `ff9d37022a310cab3eea0bb3c298e3d3ec8b0d3057f7256da4f0543dab18b53c`; Release/source `d20536db37a0`/iOS14/arm64 | Exact iPhone/iOS17 A-generating + B-send/generate test positive with `activeExecutorCount=2`; disclosure toggles single-digit ms. Main inline reasoning/tool density and default-collapsed live disclosure rejected. | **Runtime partial: tested cross-conversation simultaneous generation + disclosure performance positive; presentation rejected; permanently reserved** |\n| `DEV-send-stream-0.1.0-b73` | `DEV-send-stream` | `0.1.0 (73)` | exact source `4edda892a04a1a07f4a07e74b135b969ea82193e`; product commit `0e3eb6cad4cc56e8c2bcb946724d7cf1d4d55701`; PR #29 | Assembly `33408291419`; Push `33408695143/99542593642`; PR `33408698697/99542605699`; Artifact `9764247402`; ZIP `sha256:718c2f4fd0fe3521f7469f5996f6944960ffdaa3b2829c0c17e340ebd41dd206`; IPA `8285ba9d5f63207feb2eaf722ec722a886f3ee88956236a89a716ad58b884113`; Release/source `4edda892a04a`/iOS14/arm64 | Presentation-only correction: main timeline omits fallback generic rows but preserves meaningful service titles, uses body-scale reasoning/looser tool rhythm, live auto-opens once and exact reasoning end auto-collapses once without reasserting over later manual state; Root transport/concurrency unchanged. | **Code/scope/Simulator/Push+PR CI/Artifact/package verified; Runtime pending; permanently reserved** |'''
p.write_text(text.replace(anchor, rows, 1))

# PROJECT_SPECIFIC_RULES
p = Path("docs/project/PROJECT_SPECIFIC_RULES.md")
text = p.read_text()
text = text.replace("Exact b67 implements this by using existing `activeEvents != nil` for `isBusy` and clearing `pendingSend` immediately before the one JS submit evaluation. Runtime acceptance of the correction remains pending.", "Exact b67 implements this by using existing `activeEvents != nil` for `isBusy` and clearing `pendingSend` immediately before the one JS submit evaluation. Exact b67 production transport Runtime is accepted for the recorded existing-conversation scope.")
old_tool = '''- GitHub connector visible tool input/output mapping is authorized only for the b63-b65 evidenced exact-parent GitHub shape.\n- authorized GitHub input = invocation `metadata.connector_tool_payload`.\n- authorized GitHub output = exact-parent matched completed result `message.content`.\n- `工具输入` / `工具输出` may use independent nested disclosures and decoded hierarchical output; presentation must not silently truncate authorized paired content merely to reduce density.\n- do not generalize expandable raw detail to another connector family until separately evidenced.\n'''
new_tool = '''- GitHub connector raw input/output mapping remains authorized only for the b63-b65 evidenced exact-parent GitHub shape.\n- authorized GitHub input = invocation `metadata.connector_tool_payload`.\n- authorized GitHub output = exact-parent matched completed result `message.content`; current b72+ product requirement deliberately does **not** present tool output in the normal tool-list sheet. Retaining authorized source data for response association does not require showing it.\n- main inline reasoning is semantic: show only meaningful service-authored tool-purpose titles; omit fallback `工具调用` rows from the main surface without deleting the ordered tool list; never synthesize/merge titles by guess.\n- clicking a concrete main tool row opens the current assistant turn's ordered tools-only list; authorized input is shown directly without a `工具输入` disclosure/title; no reasoning prose and no tool-output UI.\n- do not generalize raw connector detail to another connector family until separately evidenced.\n'''
if text.count(old_tool) != 1:
    raise SystemExit("project rules tool anchor mismatch")
text = text.replace(old_tool, new_tool, 1)
text = text.replace("- b24-b67 emitted identities are permanently reserved;", "- b24-b73 emitted identities are permanently reserved;")
text = text.replace("- exact b67 package authority is `0.1.0 (67)`, source `52ab38f16fe914ef8316bb1dc712b77c2c87a271`, Artifact `9739891865`, IPA `3712dec92cddfe64e84fc797e1506d83231cd878633b932b9acf0e7381795497`; Runtime pending;\n- do not allocate b68 before exact b67 Runtime supplies a concrete need.", "- exact b67 package authority is `0.1.0 (67)`, source `52ab38f16fe914ef8316bb1dc712b77c2c87a271`, Artifact `9739891865`, IPA `3712dec92cddfe64e84fc797e1506d83231cd878633b932b9acf0e7381795497`; production transport Runtime accepted for the recorded scope;\n- exact b73 package authority is `0.1.0 (73)`, source `4edda892a04a1a07f4a07e74b135b969ea82193e`, Artifact `9764247402`, IPA `8285ba9d5f63207feb2eaf722ec722a886f3ee88956236a89a716ad58b884113`; Runtime presentation pending;\n- do not allocate b74 before exact b73 Runtime supplies a concrete need.")
p.write_text(text)

print("b73 durable docs patched")
