from pathlib import Path

adapter = Path('docs/project/WEB_SEND_ADAPTER.md')
text = adapter.read_text()
anchor = "Official no-resend `/backend-api/f/conversation/resume` remains a separate b45-b47 continuation/recovery evidence surface. It is not a substitute for the first protected Send and its native parity remains unverified.\n"
insert = anchor + "\n### Cross-device active-response continuation — 2026-09-01 Runtime evidence\n\nA current Web Rule Lab capture now confirms the official page behavior when another platform has already started a response and the user enters the same conversation in official Web:\n\n- the page opens a user-level `wss://ws.chatgpt.com/...` socket and receives short string frames; this capture does **not** establish that socket as the reasoning/final body transport;\n- on entering the target conversation, the page issues the normal conversation/detail bootstrap plus `GET /backend-api/conversation/{conversation_id}/stream_status` -> HTTP200 JSON;\n- when the response is still active, the page itself issues `POST /backend-api/f/conversation/resume`;\n- the observed request JSON shape is exactly `{ conversation_id, offset }`;\n- the resume response is HTTP200 `text/event-stream`;\n- no second `/backend-api/f/conversation` Send is required for this adoption path.\n\n**Current production rule:** external active-response adoption may observe and parse the official page's own `/backend-api/f/conversation/resume` SSE for the currently targeted conversation. Native code must not construct the resume request, choose/synthesize `offset`, replay browser/session headers, or poll `stream_status`. The page remains transport authority; `ConversationRepository` becomes/retains the sole Native response lifecycle owner once that page-owned resume is observed. Only a resume whose request `conversation_id` matches the executor's authoritative target may be adopted. The user-level WebSocket remains structural evidence only and is not authorized as a Native response-body source from this capture.\n"
if anchor not in text:
    raise SystemExit('adapter anchor missing')
text = text.replace(anchor, insert, 1)
adapter.write_text(text)

checkpoint = Path('docs/project/current/dev/DEV-send-stream.md')
text = checkpoint.read_text()
old = "Historical b45 Runtime proves the official browser has a no-resend continuation route `POST /backend-api/f/conversation/resume` with `{conversation_id, offset}` returning HTTP200 SSE and normal terminal grammar after an interrupted response. It does **not** prove that current cross-device live adoption uses `/resume`, what the current offset is, or whether Web now uses WebSocket/another page-owned transport for this case. The user's current observation proves official Web can receive the state, but not the exact transport shape.\n\nTherefore b74 must not guess `/resume`, add polling, or synthesize a fake `正在思考`. Before external-adoption product code, use the existing Web Rule Lab/current official page to capture the smallest structural evidence identifying the actual page-owned cross-device continuation mechanism. Once identified, the intended ownership remains:\n"
new = "The 2026-09-01 Web Rule Lab capture now closes that transport-shape gap for the tested cross-device case. After another platform started the response and official Web entered the same conversation, the page opened its normal user-level WebSocket, loaded conversation/bootstrap state, requested `GET /backend-api/conversation/{id}/stream_status` (HTTP200 JSON), then issued **page-owned** `POST /backend-api/f/conversation/resume` with request JSON keys exactly `conversation_id` + `offset`; that request returned HTTP200 `text/event-stream`. The capture did not expose response bodies or secret header values. Short WebSocket frames were observed but are not proven to carry the reasoning/final body.\n\nTherefore b74 is now authorized to observe the official page's own `/resume` SSE for external active-response adoption. Native must **not** construct the resume request, derive/guess `offset`, poll `stream_status`, or issue a second Send. The bridge must verify the page-owned resume targets the executor's current authoritative conversation before adopting it. Intended ownership remains:\n"
if old not in text:
    raise SystemExit('checkpoint evidence anchor missing')
text = text.replace(old, new, 1)
old2 = "3. External active-response adoption: **probe first**. Product source changes only after the current official browser transport shape is evidenced. Likely integration surfaces are `RootViewController.swift` covered executor + existing Repository response runtime, but no route/mechanism is authorized yet.\n"
new2 = "3. External active-response adoption: current Runtime now authorizes observing the page-owned `/backend-api/f/conversation/resume` SSE for the executor's current authoritative conversation. Integration surfaces are `RootViewController.swift` covered executor + existing Repository response runtime. Native request construction/offset synthesis/polling remain prohibited.\n"
if old2 not in text:
    raise SystemExit('checkpoint scope anchor missing')
text = text.replace(old2, new2, 1)
old3 = "2. **Next:** implement and statically audit only the evidence-backed geometry reuse + tool-spacing changes on a tooling assembly branch from this checkpoint head.\n3. **Then:** obtain current official-Web structural evidence for externally initiated active-response continuation using Web Rule Lab; update `WEB_SEND_ADAPTER.md` rule only if evidence supports a specific mechanism.\n4. **Then:** implement the smallest Repository-owned external-adoption bridge, run scope/diff/compile checks, promote one clean b74 product/config source, Push+PR CI, Artifact/package verification.\n"
new3 = "2. **Confirmed complete:** geometry reuse + tool-spacing patch assembled on tooling branch; run `33414597158 / 99562115400` passed scope, `git diff --check` and Xcode 16.4 Simulator build, producing code commit `894eea1` on `assembly/dev-send-stream-b74-ui-product-20260901`. This is compile evidence only, not the final b74 product source.\n3. **Confirmed complete:** current Web Rule Lab cross-device capture proves page-owned `POST /backend-api/f/conversation/resume` `{conversation_id, offset}` -> HTTP200 SSE after `stream_status`; WebSocket remains non-authoritative structural evidence.\n4. **Next:** reassemble the UI patch plus the smallest page-owned-resume observation / Repository external-adoption bridge from the updated checkpoint, run scope/diff/compile checks, then promote one clean b74 product/config source, Push+PR CI, Artifact/package verification.\n"
if old3 not in text:
    raise SystemExit('checkpoint batch anchor missing')
text = text.replace(old3, new3, 1)
old4 = "Implement the deterministic geometry-reuse + tool-spacing patch and prepare the smallest Web Rule Lab probe for the external-platform active-generation reproduction. If the probe identifies the official continuation transport, implement that exact mechanism in b74; otherwise stop at the genuine human probe evidence gate rather than guessing.\n"
new4 = "Reassemble the already-compiled geometry-reuse/tool-spacing patch together with the newly authorized page-owned `/backend-api/f/conversation/resume` observation path. External adoption must create one Repository live-response generation only after a matching page-owned resume is observed, consume the existing parser events, reconcile once at terminal, and add no native resume request, offset synthesis, polling, retry, timer, second Send or second response store.\n"
if old4 not in text:
    raise SystemExit('checkpoint next-action anchor missing')
text = text.replace(old4, new4, 1)
checkpoint.write_text(text)
